# Generated by Django 4.2.7 on 2023-11-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comentario_autor_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='etiqueta',
            field=models.CharField(default='Mi primera etiqueta', max_length=255),
        ),
    ]
