# Generated by Django 4.2.7 on 2023-11-23 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_publicacion_etiqueta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='etiqueta',
        ),
    ]
