# Generated by Django 4.2.7 on 2023-12-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comentario_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
