# Generated by Django 4.2.7 on 2023-12-01 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_categoria_slug_publicacion_avatar_publicacion_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='avatar',
            new_name='imagen',
        ),
    ]
